apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  namespace: dev2406
 # nodeName: master
spec:
  nodeName: master
  containers:
  - name: secret
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret
