#Create a pod called my-busybox in the dev2406 namespace using the busybox image. The container should be called secret and should sleep for 3600 seconds.

#The container should mount a read-only secret volume called secret-volume at the path /etc/secret-volume. The secret being mounted has already been created for you and is called dotfile-secret.

#Make sure that the pod is scheduled on master and no other node in the cluster.



apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  namespace: dev2406
 # nodeName: master
spec:
  nodeName: master
  containers:
  - name: secret
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret
