#Create a single ingress resource called ingress-vh-routing. The resource should route HTTP traffic to multiple hostnames as specified below:

#The service video-service should be accessible on http://watch.ecom-store.com:30093/video

#The service apparels-service should be accessible on http://apparels.ecom-store.com:30093/wear

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-vh-routing
spec:
  rules:
  - host: watch.ecom-store.com
    http:
      paths:
      - path: /video
        backend:
          serviceName: video-service
          servicePort: 8080
  - host: apparels.ecom-store.com
    http:
      paths:
      - path: /wear
        backend:
          serviceName: apparels-service
          servicePort: 8080
